### ISSUE TITLE
how do i interact with a document? 

### ISSUE THREAD

**Issue by jersam** [JLeine/open-webui#9]
I have SecureAI tools working and I'm able to select a document directly then ask questions for the model and get my reply. 

How can I do this with the tool you created?

**Comment by JLeine** [comment]
Hi @jersam 
Have you looked at my readme file? Or more specifically this screenshot?
https://github.com/JLeine/open-webui/blob/main/docs/paperless/query-tool.png

This should give you an idea of how to use the tool. It depends on your documents within paperless and how you have tagged or categorised them.

**Comment by jersam** [comment]
Yes of course.

This project https://github.com/SecureAI-Tools/SecureAI-Tools let's you
interface to the document from search,  find the document,  select it and
ask questions.


I didn't see this function
